spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring3product
    username: spring3
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # para nao gerar log de erro sem ser erro


